title: E.P.I.T.O.M.E. Docs
description: Documentation for the EPITOME pipeline
theme: just-the-docs

url: https://github.com/DOH-JDJ0303/epitome-docs

baseurl: "/epitome-docs"

favicon_ico: "/assets/media/epitome-logo.ico"

aux_links:
  VAPER GitHub: https://github.com/DOH-JDJ0303/epitome

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: red
  example:
    title: Example
    color: yellow